### PR TITLE
Changed the way to initialize neovim

### PR DESCRIPTION
**Pull request by drehren**
- Now messages before nvim_ui_attach are sync
- Added VimEnter autocommand (to setup after user config load)
- Fixed some MSVC warnings

### CODE REVIEW

**Comment by drehren** [comment]
The idea behind this change is to allow a  procedural initialization of the editor.
This could allow the elimination of the request vector for initialization

**Comment by mg979** [comment]
I believe this PR broke `guifont` somehow (it now requires being set into a `VimEnter` autocommand in my vimrc).

**Comment by RMichelsen** [comment]
> I believe this PR broke `guifont` somehow (it now requires being set into a `VimEnter` autocommand in my vimrc).

Did you try the new release or just this PR? I cannot reproduce with the newest Release.

**Comment by drehren** [comment]
Hi can you share an init.vim or init,lua file that reproduces your issue? I've just tested this with a minimal config (only set guifont) file with the -u flag and it worked correctly.

**Comment by mg979** [comment]
> Did you try the new release or just this PR? I cannot reproduce with the newest Release.

The new release, not just the PR. I've been assuming it's this PR because I saw it removed some guifont-related code.

> Hi can you share an init.vim or init,lua file that reproduces your issue?

This breaks it already on my PC:
```
set rtp=$VIMRUNTIME noloadplugins

if 1
    set guifont=DejaVuSansMono\ NF:h12:cANSI:qDRAFT
else
    set guifont=Hack\ Nerd\ Font\ Mono:h11:cANSI:qDRAFT
endif
```

I use a conditional because I have 2 machines with different screen sizes, so I use different fonts. If I don't use the conditional, then it works (strangely).

Also if I do

    nvy --clean

or also

    nvy -u NONE

and then press `:` immediately after (to enter the command line) the window resizes badly. These issues aren't present in the previous release.

**Pull request merged**
